apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/my-cluster/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
