apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-helm
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/my-cluster/flux-helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
