apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-helmrepos
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/my-cluster/flux-helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  resources:
    - helmrepo-bitnami.yaml
    - helmrepo-cloudnative-pg.yaml
