apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../flux-helm/helmrelease-cloudnative-pg.yaml
  - ../../flux-helm/helmrelease-n8n-staging.yaml
  - ingress.yaml
